import 'package:dartz/dartz.dart';
import '../../../data/models/chat_model/chat_model.dart';
import '../../../data/models/chat_model/send_message_model.dart';
import '../../../data/models/conversation_model/conversation.dart';
import '../../../data/models/member_model.dart';
import '../../../utils/failures.dart';
import '../../repositories/chat_repository.dart';

part 'get_conversation_message.dart';
part 'get_conversations.dart';
part 'get_member_info.dart';
part 'get_unread_message_count.dart';
part 'send_instant_message.dart';
part 'delete_conversations.dart';
part 'set_conversations_favorite.dart';
part 'get_conversations_between_user.dart';
part 'unset_convertsations_favorite.dart';
part 'block_user.dart';
part 'unblock_user.dart';
